### ISSUE TITLE
fix umd/amd code

### ISSUE THREAD

**Issue by geromueller** [rse/vue-params#1]
Hi,

your umd/amd prefix is not detected by webpack. Could you use the default prefix:

(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory() :
  typeof define === 'function' && define.amd ? define(factory) :
  (global.VueRouter = factory());
}

**Comment by rse** [comment]
Are you sure? I've used VueParam + VueI18Next with WebPack just fine. At least with WebPack 2.1.0 beta 25. So, can it be that you used an older WebPack version? I ask because I use this particular UMD header in a dozen libraries...

**Comment by geromueller** [comment]
I use 1.13.3 (stable).:

main.js:31320 Uncaught Error: define cannot be used indirect
    at module.exports (http://localhost:8081/static/main.js:31320:38)
    at VueParams.install.paramValue (http://localhost:8081/static/main.js:31240:34)
    at Object.<anonymous> (http://localhost:8081/static/main.js:31247:3)
    at **webpack_require** (http://localhost:8081/static/main.js:20:30)
    at Object.<anonymous> (http://localhost:8081/static/main.js:7764:14)
    at **webpack_require** (http://localhost:8081/static/main.js:20:30)
    at Object.<anonymous> (http://localhost:8081/static/main.js:48:19)
    at **webpack_require** (http://localhost:8081/static/main.js:20:30)
    at http://localhost:8081/static/main.js:40:18
    at http://localhost:8081/static/main.js:43:10

Am Sonntag, 20. November 2016, 06:45:26 CET schrieb Ralf S. Engelschall:

> Are you sure? I've used VueParam + VueI18Next with WebPack just fine. At least with WebPack 2.1.0 beta 25. So, can it be that you used an older WebPack version?

**Comment by ryanweal** [comment]
I'm seeing this issue and I am new to webpack with Vue. Running stable version because I'm just following documentation.

**Comment by Matheo13** [comment]
I have the same issue.
`Uncaught Error: define cannot be used indirect`
webpack 2.2.1
vue-params 0.9.2


works with `
				{
						test: require.resolve('vue-params'),
				    loader: 'imports-loader?define=>false'
				}
`
https://webpack.js.org/loaders/imports-loader/#disable-amd

**Comment by stepbeta** [comment]
I'm having the same problem, and Matheo13's suggestion doesn't work for me, although I've got his same versions.

It gives me
```
This dependency was not found:
* vue-params in ./src/main.js
To install it, you can run: npm install --save vue-params
```

But vue-params is in the dependencies section of my package json.

main.js:
```javascript
import Vue from 'vue';
import Vuex from 'vuex';
import VueParams from 'vue-params';
```

**Comment by stepbeta** [comment]
Same problem here, and Matheo13's suggestion doesn't work for me

**Comment by appleseedexm** [comment]
Which version of Webpack are you running?
Alternatively, with WP2, you can [completely disable AMD in Webpack](https://webpack.js.org/configuration/module/#rule-parser) if you dont need it:

```
module: {
    rules: [
      {
        parser: {amd: false}
      }
    ]
}
```

**Comment by knpwrs** [comment]
@appleseedexm's solution works. That said, I think a better solution than "fixing" the UMD code would be to make the module a webpack build targeting UMD with any external libs marked as such. Why bother manually dealing with UMD code?

**Comment by komali2** [comment]
I'm currently having this issue.
